export const PLACEHOLDER_IMG = 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="600" height="800" viewBox="0 0 600 800"%3E%3Cdefs%3E%3ClinearGradient id="g" x1="0%25" y1="0%25" x2="100%25" y2="100%25"%3E%3Cstop offset="0%25" style="stop-color:%23f8f0e3;stop-opacity:1"%3E%3C/stop%3E%3Cstop offset="100%25" style="stop-color:%23e8d5c4;stop-opacity:1"%3E%3C/stop%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width="600" height="800" fill="url(%23g)"/%3E%3Ctext x="300" y="400" text-anchor="middle" fill="%23997b66" font-family="serif" font-size="24"%3EYEZ BEE%3C/text%3E%3C/svg%3E';

export const SAMPLE_PRODUCTS = [
  {
    id: 'prod-1',
    name: 'Ivory Silk Kanjeevaram Saree',
    slug: 'ivory-silk-kanjeevaram-saree',
    description: 'Handwoven pure silk saree with intricate gold zari work. Features a rich traditional border and elaborate pallu design. Perfect for weddings and festive occasions.',
    images: [PLACEHOLDER_IMG, PLACEHOLDER_IMG, PLACEHOLDER_IMG],
    price: 45000,
    originalPrice: 58000,
    colors: [
      { name: 'Ivory', hex: '#FFFFF0', image: PLACEHOLDER_IMG },
      { name: 'Gold', hex: '#D4AF37', image: PLACEHOLDER_IMG },
      { name: 'Blush Pink', hex: '#FADADD', image: PLACEHOLDER_IMG },
    ],
    sizes: ['Free Size'],
    fabrics: ['Silk'],
    occasions: ['Wedding', 'Festival', 'Engagement'],
    inStock: true,
    quantity: 15,
    sku: 'YBS-001',
    rating: 4.8,
    reviewCount: 124,
    isFeatured: true,
    isNewArrival: false,
    isOnSale: true,
    discount: 22,
    category: 'sarees',
    brand: 'YEZ BEE Signature',
  },
  {
    id: 'prod-2',
    name: 'Ruby Red Velvet Lehenga',
    slug: 'ruby-red-velvet-lehenga',
    description: 'Opulent velvet lehenga set in deep ruby red. Features intricate hand-embroidery with zardozi and dabka work. Includes blouse and dupatta.',
    images: [PLACEHOLDER_IMG, PLACEHOLDER_IMG, PLACEHOLDER_IMG],
    price: 78000,
    originalPrice: 95000,
    colors: [
      { name: 'Ruby Red', hex: '#9B111E', image: PLACEHOLDER_IMG },
      { name: 'Emerald', hex: '#046307', image: PLACEHOLDER_IMG },
      { name: 'Midnight Blue', hex: '#191970', image: PLACEHOLDER_IMG },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    fabrics: ['Velvet'],
    occasions: ['Wedding', 'Reception', 'Sangeet'],
    inStock: true,
    quantity: 8,
    sku: 'YBS-002',
    rating: 4.9,
    reviewCount: 89,
    isFeatured: true,
    isNewArrival: true,
    isOnSale: true,
    discount: 18,
    category: 'lehengas',
    brand: 'YEZ BEE Couture',
  },
  {
    id: 'prod-3',
    name: 'Champagne Georgette Gown',
    slug: 'champagne-georgette-gown',
    description: 'Elegant floor-length gown in champagne georgette. Adorned with delicate sequin work and a flowing trail. Features a sweetheart neckline.',
    images: [PLACEHOLDER_IMG, PLACEHOLDER_IMG, PLACEHOLDER_IMG],
    price: 35000,
    colors: [
      { name: 'Champagne', hex: '#F7E7CE', image: PLACEHOLDER_IMG },
      { name: 'Dusty Rose', hex: '#C9A9A6', image: PLACEHOLDER_IMG },
      { name: 'Mauve', hex: '#B784A7', image: PLACEHOLDER_IMG },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    fabrics: ['Georgette'],
    occasions: ['Cocktail', 'Party', 'Reception'],
    inStock: true,
    quantity: 20,
    sku: 'YBS-003',
    rating: 4.6,
    reviewCount: 67,
    isFeatured: false,
    isNewArrival: true,
    isOnSale: false,
    discount: 0,
    category: 'western-gowns',
    brand: 'YEZ BEE',
  },
  {
    id: 'prod-4',
    name: 'Navy Blue Indo-Western Gown',
    slug: 'navy-blue-indo-western-gown',
    description: 'Contemporary Indo-western gown with a fusion silhouette. Features intricate threadwork and a modern asymmetric hemline.',
    images: [PLACEHOLDER_IMG, PLACEHOLDER_IMG, PLACEHOLDER_IMG],
    price: 42000,
    originalPrice: 52000,
    colors: [
      { name: 'Navy', hex: '#1E3A5F', image: PLACEHOLDER_IMG },
      { name: 'Burgundy', hex: '#800020', image: PLACEHOLDER_IMG },
      { name: 'Forest Green', hex: '#228B22', image: PLACEHOLDER_IMG },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    fabrics: ['Crepe', 'Net'],
    occasions: ['Sangeet', 'Party', 'Cocktail', 'Mehendi'],
    inStock: true,
    quantity: 12,
    sku: 'YBS-004',
    rating: 4.7,
    reviewCount: 93,
    isFeatured: true,
    isNewArrival: false,
    isOnSale: true,
    discount: 19,
    category: 'indo-western',
    brand: 'YEZ BEE Signature',
  },
  {
    id: 'prod-5',
    name: 'Pastel Pink Organza Saree',
    slug: 'pastel-pink-organza-saree',
    description: 'Dreamy pastel pink organza saree with floral motif embroidery. Lightweight and ethereal, perfect for daytime weddings and receptions.',
    images: [PLACEHOLDER_IMG, PLACEHOLDER_IMG, PLACEHOLDER_IMG],
    price: 28000,
    originalPrice: 34000,
    colors: [
      { name: 'Pastel Pink', hex: '#FADADD', image: PLACEHOLDER_IMG },
      { name: 'Lavender', hex: '#E6E6FA', image: PLACEHOLDER_IMG },
      { name: 'Mint', hex: '#98FF98', image: PLACEHOLDER_IMG },
    ],
    sizes: ['Free Size'],
    fabrics: ['Organza'],
    occasions: ['Engagement', 'Mehendi', 'Haldi', 'Festival'],
    inStock: true,
    quantity: 25,
    sku: 'YBS-005',
    rating: 4.5,
    reviewCount: 156,
    isFeatured: false,
    isNewArrival: true,
    isOnSale: true,
    discount: 18,
    category: 'sarees',
    brand: 'YEZ BEE',
  },
  {
    id: 'prod-6',
    name: 'Gold Embroidered Blouse',
    slug: 'gold-embroidered-blouse',
    description: 'Handcrafted blouse piece with heavy gold thread embroidery. Features a classic round neck and three-quarter sleeves. Custom stitching available.',
    images: [PLACEHOLDER_IMG, PLACEHOLDER_IMG, PLACEHOLDER_IMG],
    price: 8500,
    originalPrice: 12000,
    colors: [
      { name: 'Gold', hex: '#D4AF37', image: PLACEHOLDER_IMG },
      { name: 'Silver', hex: '#C0C0C0', image: PLACEHOLDER_IMG },
      { name: 'Copper', hex: '#B87333', image: PLACEHOLDER_IMG },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    fabrics: ['Silk', 'Satin'],
    occasions: ['Wedding', 'Engagement', 'Party', 'Festival'],
    inStock: true,
    quantity: 50,
    sku: 'YBS-006',
    rating: 4.4,
    reviewCount: 203,
    isFeatured: false,
    isNewArrival: false,
    isOnSale: true,
    discount: 29,
    category: 'blouses',
    brand: 'YEZ BEE',
  },
  {
    id: 'prod-7',
    name: 'Emerald Green Lehenga Choli',
    slug: 'emerald-green-lehenga-choli',
    description: 'Stunning emerald green lehenga set with traditional gota patti work. Lightweight fabric with a rich silk dupatta. Perfect for festive celebrations.',
    images: [PLACEHOLDER_IMG, PLACEHOLDER_IMG, PLACEHOLDER_IMG],
    price: 55000,
    originalPrice: 65000,
    colors: [
      { name: 'Emerald', hex: '#046307', image: PLACEHOLDER_IMG },
      { name: 'Peacock Blue', hex: '#004F54', image: PLACEHOLDER_IMG },
      { name: 'Hot Pink', hex: '#FF1493', image: PLACEHOLDER_IMG },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    fabrics: ['Silk', 'Georgette'],
    occasions: ['Wedding', 'Sangeet', 'Festival', 'Reception'],
    inStock: true,
    quantity: 10,
    sku: 'YBS-007',
    rating: 4.7,
    reviewCount: 78,
    isFeatured: true,
    isNewArrival: false,
    isOnSale: true,
    discount: 15,
    category: 'lehengas',
    brand: 'YEZ BEE Couture',
  },
  {
    id: 'prod-8',
    name: 'White Lace Detailed Kurti',
    slug: 'white-lace-detailed-kurti',
    description: 'Elegant white kurti with delicate lace panels and embroidered neckline. Paired with straight pants and a organza dupatta.',
    images: [PLACEHOLDER_IMG, PLACEHOLDER_IMG, PLACEHOLDER_IMG],
    price: 5500,
    colors: [
      { name: 'White', hex: '#FFFFFF', image: PLACEHOLDER_IMG },
      { name: 'Sky Blue', hex: '#87CEEB', image: PLACEHOLDER_IMG },
      { name: 'Peach', hex: '#FFCBA4', image: PLACEHOLDER_IMG },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    fabrics: ['Cotton', 'Linen'],
    occasions: ['Casual', 'Office Wear', 'Party'],
    inStock: true,
    quantity: 35,
    sku: 'YBS-008',
    rating: 4.3,
    reviewCount: 45,
    isFeatured: false,
    isNewArrival: true,
    isOnSale: false,
    discount: 0,
    category: 'kurtas',
    brand: 'YEZ BEE',
  },
  {
    id: 'prod-9',
    name: 'Statement Chandbali Earrings',
    slug: 'statement-chandbali-earrings',
    description: 'Handcrafted oversized chandbali earrings with intricate enamel work and pearl drops. Lightweight with secure screw-back closure.',
    images: [PLACEHOLDER_IMG, PLACEHOLDER_IMG, PLACEHOLDER_IMG],
    price: 14900,
    originalPrice: 18000,
    colors: [
      { name: 'Gold', hex: '#D4AF37', image: PLACEHOLDER_IMG },
      { name: 'Rose Gold', hex: '#B76E79', image: PLACEHOLDER_IMG },
    ],
    sizes: ['Free Size'],
    fabrics: [],
    occasions: ['Wedding', 'Engagement', 'Sangeet', 'Reception', 'Party'],
    inStock: true,
    quantity: 30,
    sku: 'YBS-009',
    rating: 4.6,
    reviewCount: 112,
    isFeatured: false,
    isNewArrival: false,
    isOnSale: true,
    discount: 17,
    category: 'accessories',
    brand: 'YEZ BEE Accessories',
  },
  {
    id: 'prod-10',
    name: 'Bridal Red Banarasi Saree',
    slug: 'bridal-red-banarasi-saree',
    description: 'Heirloom-quality Banarasi silk saree in bridal red. Woven with pure zari in traditional floral and paisley motifs. Includes matching blouse piece.',
    images: [PLACEHOLDER_IMG, PLACEHOLDER_IMG, PLACEHOLDER_IMG],
    price: 95000,
    originalPrice: 125000,
    colors: [
      { name: 'Bridal Red', hex: '#8B0000', image: PLACEHOLDER_IMG },
      { name: 'Maroon', hex: '#800020', image: PLACEHOLDER_IMG },
      { name: 'Gold', hex: '#D4AF37', image: PLACEHOLDER_IMG },
    ],
    sizes: ['Free Size'],
    fabrics: ['Silk'],
    occasions: ['Wedding', 'Reception'],
    inStock: true,
    quantity: 5,
    sku: 'YBS-010',
    rating: 4.9,
    reviewCount: 46,
    isFeatured: true,
    isNewArrival: true,
    isOnSale: true,
    discount: 24,
    category: 'sarees',
    brand: 'YEZ BEE Heritage',
  },
];

export const SAMPLE_CATEGORIES = [
  { id: 'cat-1', name: 'Sarees', slug: 'sarees', description: 'Handcrafted silk, organza, and georgette sarees for every occasion.', image: PLACEHOLDER_IMG, productCount: 120 },
  { id: 'cat-2', name: 'Lehengas', slug: 'lehengas', description: 'Exquisite bridal and festive lehenga sets with intricate craftsmanship.', image: PLACEHOLDER_IMG, productCount: 85 },
  { id: 'cat-3', name: 'Western Gowns', slug: 'western-gowns', description: 'Elegant floor-length gowns for cocktails and formal events.', image: PLACEHOLDER_IMG, productCount: 64 },
  { id: 'cat-4', name: 'Indo-Western', slug: 'indo-western', description: 'Contemporary fusion wear blending traditional and modern aesthetics.', image: PLACEHOLDER_IMG, productCount: 48 },
  { id: 'cat-5', name: 'Blouses', slug: 'blouses', description: 'Designer blouses with intricate embroidery and embellishments.', image: PLACEHOLDER_IMG, productCount: 110 },
  { id: 'cat-6', name: 'Accessories', slug: 'accessories', description: 'Statement jewellery, clutches, and more to complete your look.', image: PLACEHOLDER_IMG, productCount: 200 },
  { id: 'cat-7', name: 'Kurtas & Tunics', slug: 'kurtas', description: 'Comfortable yet stylish ethnic tops for daily elegance.', image: PLACEHOLDER_IMG, productCount: 92 },
  { id: 'cat-8', name: 'Anarkalis', slug: 'anarkalis', description: 'Floor-length anarkali suits with classic and contemporary designs.', image: PLACEHOLDER_IMG, productCount: 56 },
];

export const SAMPLE_REVIEWS = [
  { id: 'rev-1', productId: 'prod-1', author: 'Priya S.', rating: 5, title: 'Absolutely Stunning!', body: 'The silk quality is exceptional. The gold zari work is even more beautiful in person. Received so many compliments at my sister\'s wedding.', date: '2026-03-15', verified: true },
  { id: 'rev-2', productId: 'prod-1', author: 'Ananya M.', rating: 4, title: 'Beautiful saree, slightly heavy', body: 'The craftsmanship is superb. It is a bit heavy due to the zari work but totally worth it for special occasions.', date: '2026-02-28', verified: true },
  { id: 'rev-3', productId: 'prod-2', author: 'Ritu K.', rating: 5, title: 'Dream Lehenga!', body: 'Wore this for my reception and it was perfect. The velvet is so soft and the embroidery is exquisite.', date: '2026-04-02', verified: true },
  { id: 'rev-4', productId: 'prod-2', author: 'Neha G.', rating: 5, title: 'Worth every penny', body: 'The fit is perfect and the color is rich. Felt like a queen wearing this.', date: '2026-01-20', verified: true },
  { id: 'rev-5', productId: 'prod-4', author: 'Deepika R.', rating: 4, title: 'Love the fusion design', body: 'Great contemporary piece. The asymmetric hem is unique and the threadwork is beautiful. Sizing runs slightly large.', date: '2026-03-30', verified: true },
  { id: 'rev-6', productId: 'prod-6', author: 'Shreya P.', rating: 5, title: 'Best blouse ever!', body: 'The gold embroidery is so intricate. Got it stitched locally and it turned out gorgeous. Great value for money.', date: '2026-02-10', verified: true },
  { id: 'rev-7', productId: 'prod-5', author: 'Kavita D.', rating: 4, title: 'Very pretty and light', body: 'Perfect for daytime events. The organza is soft and the floral motifs are delicate and beautiful.', date: '2026-04-15', verified: true },
  { id: 'rev-8', productId: 'prod-9', author: 'Meera J.', rating: 5, title: 'Statement pieces', body: 'These earrings are huge and gorgeous. Lightweight despite the size. Got so many compliments!', date: '2026-03-05', verified: true },
];

export const SAMPLE_ORDERS = [
  {
    id: 'ORD-2026-001',
    userId: 'user-1',
    items: [
      { productId: 'prod-1', name: 'Ivory Silk Kanjeevaram Saree', variant: { color: 'Ivory', size: 'Free Size' }, quantity: 1, price: 45000 },
      { productId: 'prod-6', name: 'Gold Embroidered Blouse', variant: { color: 'Gold', size: 'M' }, quantity: 1, price: 8500 },
    ],
    shippingAddress: { fullName: 'Ananya Sharma', phone: '9876543210', street: '42, Palm Grove Apartments', city: 'Mumbai', state: 'Maharashtra', pincode: '400001', country: 'India' },
    paymentMethod: 'card',
    subtotal: 53500,
    shipping: 0,
    tax: 6420,
    discount: 0,
    total: 59920,
    status: 'delivered',
    createdAt: '2026-03-10T10:30:00Z',
    updatedAt: '2026-03-15T14:00:00Z',
    estimatedDelivery: '2026-03-16',
  },
  {
    id: 'ORD-2026-002',
    userId: 'user-1',
    items: [
      { productId: 'prod-2', name: 'Ruby Red Velvet Lehenga', variant: { color: 'Ruby Red', size: 'M' }, quantity: 1, price: 78000 },
    ],
    shippingAddress: { fullName: 'Priya Kapoor', phone: '9988776655', street: '7, Lake View Colony', city: 'Delhi', state: 'Delhi', pincode: '110001', country: 'India' },
    paymentMethod: 'upi',
    subtotal: 78000,
    shipping: 0,
    tax: 9360,
    discount: 14040,
    total: 73320,
    status: 'shipped',
    createdAt: '2026-04-01T15:45:00Z',
    updatedAt: '2026-04-03T09:00:00Z',
    estimatedDelivery: '2026-04-08',
  },
  {
    id: 'ORD-2026-003',
    userId: 'user-1',
    items: [
      { productId: 'prod-5', name: 'Pastel Pink Organza Saree', variant: { color: 'Pastel Pink', size: 'Free Size' }, quantity: 2, price: 28000 },
    ],
    shippingAddress: { fullName: 'Ananya Sharma', phone: '9876543210', street: '42, Palm Grove Apartments', city: 'Mumbai', state: 'Maharashtra', pincode: '400001', country: 'India' },
    paymentMethod: 'cod',
    subtotal: 56000,
    shipping: 699,
    tax: 6720,
    discount: 10080,
    total: 53339,
    status: 'processing',
    createdAt: '2026-04-10T11:20:00Z',
    updatedAt: '2026-04-11T16:00:00Z',
    estimatedDelivery: '2026-04-18',
  },
  {
    id: 'ORD-2026-004',
    userId: 'user-1',
    items: [
      { productId: 'prod-8', name: 'White Lace Detailed Kurti', variant: { color: 'White', size: 'L' }, quantity: 1, price: 5500 },
      { productId: 'prod-9', name: 'Statement Chandbali Earrings', variant: { color: 'Gold', size: 'Free Size' }, quantity: 1, price: 14900 },
    ],
    shippingAddress: { fullName: 'Ananya Sharma', phone: '9876543210', street: '42, Palm Grove Apartments', city: 'Mumbai', state: 'Maharashtra', pincode: '400001', country: 'India' },
    paymentMethod: 'card',
    subtotal: 20400,
    shipping: 499,
    tax: 2448,
    discount: 0,
    total: 23347,
    status: 'pending',
    createdAt: '2026-04-18T09:15:00Z',
    updatedAt: '2026-04-18T09:15:00Z',
    estimatedDelivery: '2026-04-25',
  },
  {
    id: 'ORD-2026-005',
    userId: 'user-1',
    items: [
      { productId: 'prod-10', name: 'Bridal Red Banarasi Saree', variant: { color: 'Bridal Red', size: 'Free Size' }, quantity: 1, price: 95000 },
      { productId: 'prod-7', name: 'Emerald Green Lehenga Choli', variant: { color: 'Emerald', size: 'S' }, quantity: 1, price: 55000 },
    ],
    shippingAddress: { fullName: 'Priya Kapoor', phone: '9988776655', street: '7, Lake View Colony', city: 'Delhi', state: 'Delhi', pincode: '110001', country: 'India' },
    paymentMethod: 'netbanking',
    subtotal: 150000,
    shipping: 0,
    tax: 18000,
    discount: 37500,
    total: 130500,
    status: 'delivered',
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-02-10T18:00:00Z',
    estimatedDelivery: '2026-02-08',
  },
];

export const SAMPLE_COUPONS = [
  { id: 'cpn-1', code: 'WELCOME20', description: '20% off on your first order', discount: 20, type: 'percentage', minOrder: 5000, maxDiscount: 10000, validUntil: '2026-12-31', isActive: true },
  { id: 'cpn-2', code: 'FESTIVE1500', description: 'Flat ₹1,500 off on orders above ₹10,000', discount: 1500, type: 'flat', minOrder: 10000, maxDiscount: 1500, validUntil: '2026-05-31', isActive: true },
  { id: 'cpn-3', code: 'LUXE5000', description: 'Flat ₹5,000 off on orders above ₹25,000', discount: 5000, type: 'flat', minOrder: 25000, maxDiscount: 5000, validUntil: '2026-08-31', isActive: true },
  { id: 'cpn-4', code: 'FREEDEL', description: 'Free express shipping on orders above ₹15,000', discount: 1299, type: 'free_shipping', minOrder: 15000, maxDiscount: 1299, validUntil: '2026-12-31', isActive: true },
];
